T2: anchor prefix fixes (#22130)
Why I did it
fixes in T2 Radian Resiliency feature support checked in as part of PR #21732

Work item tracking
Microsoft ADO 31982579:

How I did it
The changes take care of following

Fix a typo which fetching chassis subtype in prefix_list script
remove root permission validation during radian status check
Input argument parsing fix during status check
during add_radian/del_radian template rendering, prefix-list entry to have prefixlen passed as an argument, instead of hardcoding it

How to verify it
Execute the prefix_list script, and make sure add/del radian entries go through as expected.
Ensure that status check doesnt require sudo
Ensure that status check fails when passed second argument
Ensure that backend code renders radian config as per expectation

diff --git a/dockers/docker-fpm-frr/base_image_files/prefix_list b/dockers/docker-fpm-frr/base_image_files/prefix_list
--- a/dockers/docker-fpm-frr/base_image_files/prefix_list
+++ b/dockers/docker-fpm-frr/base_image_files/prefix_list
@@ -35,10 +35,10 @@ check_root_privileges() {
 # Function to check if the device is supported device with type spine routers and subtype UpstreamLC
 check_spine_router() {
     type=$(sonic-cfggen -d -v DEVICE_METADATA.localhost.type)
-    sub_type=$(sonic-cfggen -d -v DEVICE_METADATA.localhost.sub_type)
-    
+    subtype=$(sonic-cfggen -d -v DEVICE_METADATA.localhost.subtype)
+
     # only supported on spine routers and UpstreamLC
-    if [[ "$type" != "SpineRouter" ||  "$sub_type" != "UpstreamLC" ]]; then
+    if [[ "$type" != "SpineRouter" ||  "$subtype" != "UpstreamLC" ]]; then
         echo "Operation is only supported on UpstreamLC of SpineRouter." >&2
         exit 1
     fi
@@ -46,7 +46,7 @@ check_spine_router() {
 
 # Function to skip operation on chassis supervisor
 skip_chassis_supervisor() {
-    if [ -f /etc/sonic/chassisdb.conf ]; then  
+    if [ -f /etc/sonic/chassisdb.conf ]; then
         echo "Skipping Operation on chassis supervisor"
         exit 0
     fi
@@ -72,12 +72,19 @@ validate_operation() {
     fi
 
     # Check if the prefix type is supported or not if the operation is not status
-    if [ $1 != "status" ]; then
-        for prefix_type in "${supported_prefix_types[@]}"; do
-        if [[ "$2" == "$prefix_type" ]]; then
-            valid_prefix_type=true
-            break
+    if [ "$1" == "status" ]; then
+        if [ -n "$2" ]; then
+            echo "No additional parameters required for status operation." >&2
+            echo ""
+            display_help
+            exit 1
         fi
+    else
+        for prefix_type in "${supported_prefix_types[@]}"; do
+            if [[ "$2" == "$prefix_type" ]]; then
+                valid_prefix_type=true
+                break
+            fi
         done
 
         if [ $valid_prefix_type == false ]; then
@@ -144,7 +151,9 @@ if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     display_help
 fi
 
-check_root_privileges
+if [ "$1" != "status" ]; then
+    check_root_privileges
+fi
 check_spine_router
 skip_chassis_supervisor
 
@@ -162,7 +171,7 @@ ASIC_CONF=/usr/share/sonic/device/$PLATFORM/asic.conf
 if [[ ($NUM_ASIC -gt 1) ]]; then
     asic=0
     while [ $asic -lt $NUM_ASIC ]
-    do        
+    do
         sub_role=`sonic-cfggen -d -v "DEVICE_METADATA['localhost']['sub_role']" -n asic$asic`
         if [ $sub_role == 'FrontEnd' ]; then
             handle_prefix_list_asic $asic $1 $2 $3
