T2-Route-Conv: Process Crash Optimization (#21587)
Fixes issue: #21586

diff --git a/dockers/docker-fpm-frr/base_image_files/TSB b/dockers/docker-fpm-frr/base_image_files/TSB
--- a/dockers/docker-fpm-frr/base_image_files/TSB
+++ b/dockers/docker-fpm-frr/base_image_files/TSB
@@ -42,6 +42,11 @@ if [ -z "$STARTED_BY_TSA_TSB_SERVICE" ]; then
      [[ $(/bin/systemctl show $service --property SubState  --value) == "running" ]]; then
       echo "Stopping $service before configuring TSB"
       systemctl stop $service
+      if sonic-db-cli STATE_DB HDEL "ALL_SERVICE_STATUS|tsa_tsb_service" "running" >/dev/null; then
+        echo "Successfully removed TSA-TSB service flag."
+      else
+        echo "Failed to remove TSA-TSB service flag!" >&2
+      fi
   fi
 fi
 
