[docker-ptf]: Update to Bookworm (#22605)
Why I did it
This PR updates the base image of docker-ptf to Bookworm.

How I did it
Modified Dockerfile

How to verify it
Automated Elastictest based tests using custom image tag.

Tested branch (Please provide the tested image version)
NA

Description for the changelog
[docker-ptf]: Update to Bookworm

Update docker-ptf Python 3 only image from bullseye to bookworm

diff --git a/dockers/docker-ptf/Dockerfile.j2 b/dockers/docker-ptf/Dockerfile.j2
--- a/dockers/docker-ptf/Dockerfile.j2
+++ b/dockers/docker-ptf/Dockerfile.j2
@@ -6,7 +6,7 @@ FROM {{ prefix }}multiarch/debian-debootstrap:arm64-stretch
 {% elif PTF_ENV_PY_VER == "mixed" %}
 FROM {{ prefix}}debian:buster
 {% else %}
-FROM {{ prefix }}debian:bullseye
+FROM {{ prefix }}debian:bookworm
 {% endif %}
 
 {% from "dockers/dockerfile-macros.j2" import install_python_wheels, copy_files, install_offending_packages %}
@@ -57,6 +57,8 @@ RUN apt-get update          \
         tcpd                  \
         libwrap0              \
         libwrap0-dev          \
+        libthrift-dev         \
+        python3-thrift        \
 {% endif %}
         less                \
         git                 \
@@ -104,6 +106,7 @@ RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
     && update-alternatives --install /usr/bin/pygettext pygettext /usr/bin/pygettext3 1
 {% endif %}
 
+COPY openbfdd-patches/ /root/openbfdd-patches/
 # Install all python modules from pypi. python-scapy is exception, ptf debian package requires python-scapy
 # TODO: Clean up this step
 RUN rm -rf /debs \
@@ -122,10 +125,6 @@ RUN rm -rf /debs \
     && python setup.py install \
     && cd .. \
     && rm -fr scapy-vxlan \
-{% else %}
-    && wget --https-only https://bootstrap.pypa.io/pip/get-pip.py \
-    && python3 get-pip.py \
-    && rm -f get-pip.py \
 {% endif %}
     && git clone https://github.com/sflow/sflowtool \
     && cd sflowtool \
@@ -138,6 +137,7 @@ RUN rm -rf /debs \
     && rm -fr sflowtool \
     && git clone https://github.com/dyninc/OpenBFDD.git \
     && cd OpenBFDD \
+    && git apply /root/openbfdd-patches/broken-build-bookworm.patch \
     && ./autogen.sh \
     && ./configure \
     && make \
@@ -179,7 +179,7 @@ RUN rm -rf /debs \
 RUN git clone https://github.com/facebook/tac_plus \
     && cd tac_plus \
     && cd tacacs-F4.0.4.28 \
-    && ./configure \
+    && ./configure LDFLAGS="-Wl,-rpath=/usr/local/lib" \
     && make install \
     && ln -s /usr/local/sbin/tac_plus /usr/sbin/tac_plus \
     && ln -s /usr/local/bin/tac_pwd /usr/sbin/tac_pwd \
@@ -189,14 +189,22 @@ COPY ["tacacs_plus", "/etc/init.d"]
 COPY ["tacacs+", "/etc/default"]
 {% endif %}
 
-{% if PTF_ENV_PY_VER == "mixed" %}
+# Workaround: Tornado installed outside of the
+# virtualenv as the call to the process API
+# Ansible -> Supervisor -> ExaBGP -> Process API
+# causes the process API to have a restricted 
+# environment without access to the virtualenv.
+{% if PTF_ENV_PY_VER == "py3" %}
+    RUN pip3 install --break-system-packages tornado
+{% endif %}
+
+
 RUN python3 -m venv --system-site-packages env-python3
 # Activating a virtualenv. The virtualenv automatically works for RUN, ENV and CMD.
 ENV VIRTUAL_ENV=/root/env-python3
 ARG BACKUP_OF_PATH="$PATH"
 ENV PATH="$VIRTUAL_ENV/bin:$PATH"
 ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONIOENCODING=UTF-8
-{% endif %}
 
 {% if PTF_ENV_PY_VER == "mixed" %}
 RUN python3 -m pip install --upgrade --ignore-installed pip
@@ -247,11 +255,21 @@ RUN pip3 install Flask \
     && pip3 install python-libpcap \
     && pip3 install enum34 \
     && pip3 install grpcio \
-    && pip3 install protobuf \
     && pip3 install six==1.16.0 \
     && pip3 install itsdangerous \
     && pip3 install retrying \
     && pip3 install jinja2
+
+# gnxi/gnmi_cli_py requires protobuf 3.20.x or lower
+# Bookworm by default use 5.29.x. Resetting it to 3.20.3
+# to avoid issues with gnmi tests.
+RUN set -e; \
+    . /etc/os-release; \
+    if [ "$VERSION_CODENAME" = "bookworm" ]; then \
+        pip install protobuf==3.20.3; \
+    else \
+        pip install protobuf; \
+    fi
 
 {% if docker_ptf_whls.strip() -%}
 # Copy locally-built Python wheel dependencies
@@ -259,11 +277,6 @@ RUN pip3 install Flask \
 
 # Install locally-built Python wheel dependencies
 {{ install_python_wheels(docker_ptf_whls.split(' ')) }}
-{% endif %}
-
-{% if PTF_ENV_PY_VER == "mixed" %}
-# Deactivating a virtualenv.
-ENV PATH="$BACKUP_OF_PATH"
 {% endif %}
 
 ## Adjust sshd settings
@@ -292,23 +305,34 @@ RUN git clone https://github.com/google/gnxi.git \
 
 COPY gnxi-patches/ gnxi/patches/
 
+
+{% if PTF_ENV_PY_VER == "mixed" %}
 RUN cd gnxi \
     && quilt push -a \
     && cd gnmi_cli_py \
-{% if PTF_ENV_PY_VER == "mixed" %}
     && pip install -r requirements.txt
 {% else %}
-    && pip3 install setuptools==51.0.0 \
-    && cat requirements.txt | grep -v futures > /tmp/requirements.txt \
-    && pip3 install -r /tmp/requirements.txt
+RUN cd gnxi \
+    && quilt push -a
 {% endif %}
 
+# Deactivating a virtualenv.
+# ENV PATH="$BACKUP_OF_PATH"
+
 # Install gnoic tool
+# Without specifying the version there is a failure
+# to determine the latest version automatically.
+#
+# root@a2014cb5bc54:~/gnoic# ./install.sh
+# Warning: Failed to verify the package: https://api.github.com/repos/karimra/gnoic/releases/latest, the version is not specified
+# Could not determine the latest release
+# Failed to install gnoic
+# For support, go to https://github.com/karimra/gnoic/issues
 RUN git clone https://github.com/karimra/gnoic.git \
     && cd gnoic \
     && git checkout 57aac3d \
     && chmod +x install.sh \
-    && ./install.sh \
+    && ./install.sh --version 0.1.0 \
     && cd .. \
     && rm -rf gnoic
 
@@ -318,24 +342,48 @@ debs/{{ deb }}{{' '}}
 {%- endfor -%}
 debs/
 
+{% if PTF_ENV_PY_VER == "mixed" %}
 RUN dpkg -i \
 {% for deb in docker_ptf_debs.split(' ') -%}
 debs/{{ deb }}{{' '}}
 {%- endfor %}
-
-{% if PTF_ENV_PY_VER == "py3" %}
-# Create symlink so that test scripts and ptf_runner invocation path
-# is same across python 2 and python 3 envs. Note that for virtual-env
-# ptf is under /root/env-python3/bin.
-# TODO - cleanup when the supported PTF image is py3only across all branches
-RUN mkdir -p /root/env-python3/bin \
-    && ln -s /usr/local/bin/ptf /usr/bin/ptf \
-    && ln -s /usr/bin/python /root/env-python3/bin/python3 \
-    && ln -s /usr/bin/python /root/env-python3/bin/python \
-    && ln -s /usr/local/bin/ptf /root/env-python3/bin/ptf
+{% else %}
+RUN dpkg -i debs/python-saithrift_0.9.4_amd64.deb
 {% endif %}
+
+# {% if PTF_ENV_PY_VER == "py3" %}
+# # Create symlink so that test scripts and ptf_runner invocation path
+# # is same across python 2 and python 3 envs. Note that for virtual-env
+# # ptf is under /root/env-python3/bin.
+# # TODO - cleanup when the supported PTF image is py3only across all branches
+# RUN mkdir -p /root/env-python3/bin \
+#     && ln -s /usr/local/bin/ptf /usr/bin/ptf \
+#     && ln -s /usr/bin/python /root/env-python3/bin/python3 \
+#     && ln -s /usr/bin/python /root/env-python3/bin/python \
+#     && ln -s /usr/local/bin/ptf /root/env-python3/bin/ptf
+# {% endif %}
+
+# There are some scripts like supervisorctl and others invoked from
+# custom Ansible modules which use exec_command to run these. Since
+# Ansible module's exec_command uses a restricted shell without sourcing
+# the profile or other rc files the PATH does not include the virtualenv.
+# This step keeps links to required binaries from /usr/local/bin to the
+# virtualenv bin directory.
+RUN set -eux; \
+  for f in /root/env-python3/bin/*; do \
+    base="$(basename "$f")"; \
+    case "$base" in \
+      python*|pip*) continue ;; \
+    esac; \
+    ln -sf "$f" "/usr/local/bin/$base"; \
+  done
+
+RUN echo "/root/env-python3/lib/python3.11/site-packages" > /usr/lib/python3/dist-packages/virtualenv.pth; \
+    echo "/root/env-python3/lib/python3.11/site-packages" > /usr/lib/python3.11/dist-packages/virtualenv.pth
+
+RUN echo "PYTHONPATH=/root/env-python3/lib/python3.11/site-packages" >> /etc/environment
 
 COPY ["*.ini", "/etc/ptf/"]
 EXPOSE 22 8009
 
-ENTRYPOINT ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
+ENTRYPOINT ["/root/env-python3/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
